version: "3.3"
services:
  web:
    image: nexus.highzap.com:8082/jerp/front-end/expense-budget-vue-pc:1.0.21
    ports:
      - 8001:80
    volumes:
      - expense-budget-vue-pc_logs:/var/log/nginx
    deploy:
      mode: replicated
      replicas: 1

volumes:
  expense-budget-vue-pc_logs: {}
